# Generated by Django 4.2.28 on 2026-06-12 15:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('image', models.FileField(blank=True, help_text='Imagen principal de la propiedad (JPG, PNG, WebP)', null=True, upload_to='real_estate/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler')], db_index=True, default='sale', max_length=20)),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('lot', 'Lote/Terreno'), ('commercial', 'Local Comercial'), ('farm', 'Finca')], db_index=True, default='house', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_offers', to='organizations.organization')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_real_estate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate_offers',
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['organization', 'is_active', 'expires_at'], name='real_estate_organiz_cd3667_idx')],
            },
        ),
    ]
