# Generated by Django 4.2.28 on 2026-07-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateoffer',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Aprobada'), ('pendiente_revision', 'Pendiente revisión'), ('rejected', 'Rechazada')], db_index=True, default='approved', max_length=32),
        ),
    ]
