# Generated by Django 4.2.28 on 2026-09-04 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_realestateoffer_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateoffer',
            name='image',
            field=models.FileField(blank=True, help_text='Imagen principal de la propiedad (JPG, PNG, WebP). Legacy file upload.', null=True, upload_to='real_estate/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
