# Generated by Django 4.2.28 on 2026-07-01 21:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_id', models.CharField(db_index=True, max_length=32)),
                ('credits_amount', models.PositiveIntegerField()),
                ('amount_cop', models.PositiveIntegerField()),
                ('mp_preference_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('credits_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('total_pending_cop', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('days_since_last_withdrawal', models.PositiveIntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'withdrawal_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionFacturacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_mercado_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva_comision', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_neto_recibido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creditos_comprados', models.PositiveIntegerField()),
                ('mp_payment_id', models.CharField(blank=True, max_length=255)),
                ('package_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='payments.paymentorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_facturacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de facturación',
                'verbose_name_plural': 'Transacciones de facturación',
                'db_table': 'transacciones_facturacion',
                'ordering': ['-created_at'],
            },
        ),
    ]
