# Generated by Django 4.2.28 on 2026-08-05 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('signature_valid', models.BooleanField(default=False)),
                ('live_mode', models.BooleanField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payment_status', models.CharField(blank=True, max_length=32)),
                ('processed_ok', models.BooleanField(default=False)),
                ('process_result', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.paymentorder')),
            ],
            options={
                'db_table': 'mercadopago_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_id', 'created_at'], name='mercadopago_resourc_a2e817_idx')],
            },
        ),
    ]
