# Generated by Django 4.2.28 on 2026-03-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('job_title', models.CharField(blank=True, db_index=True, max_length=100)),
                ('dynamic_data', models.JSONField(blank=True, default=dict, help_text='Campos personalizados definidos por la organización')),
                ('avatar', models.URLField(blank=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'profiles',
                'indexes': [models.Index(fields=['organization', 'department'], name='profiles_organiz_b5eec4_idx'), models.Index(fields=['organization', 'job_title'], name='profiles_organiz_00439d_idx'), models.Index(fields=['completion_percentage'], name='profiles_complet_3a8dd0_idx'), models.Index(fields=['dynamic_data'], name='dynamic_data_gin_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_profile_per_org'),
        ),
    ]
