# Generated by Django 4.2.28 on 2026-07-02 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField()),
                ('event_category', models.CharField(choices=[('feria', 'Feria'), ('concierto', 'Concierto'), ('negocios', 'Negocios'), ('cultural', 'Cultural'), ('gastronomico', 'Gastronómico'), ('deportivo', 'Deportivo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('is_online', models.BooleanField(default=False)),
                ('online_url', models.URLField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('organizer_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('external_link', models.URLField(blank=True)),
                ('price_info', models.CharField(blank=True, default='Gratis', max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('moderation_status', models.CharField(choices=[('approved', 'Aprobada'), ('pendiente_revision', 'Pendiente revisión'), ('rejected', 'Rechazada')], db_index=True, default='approved', max_length=32)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_listings', to='organizations.organization')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_listings',
                'ordering': ['start_datetime'],
            },
        ),
    ]
