# Generated by Django 4.2.28 on 2026-03-03 20:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('remote', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Medio tiempo'), ('contract', 'Contrato'), ('freelance', 'Freelance'), ('internship', 'Prácticas')], default='full_time', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='organizations.organization')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_offers',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cv_file', models.FileField(help_text='PDF máximo 1MB', upload_to='cvs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('interview', 'Entrevista'), ('rejected', 'Rechazado'), ('hired', 'Contratado')], default='pending', max_length=20)),
                ('recruiter_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer')),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['organization', 'is_active', 'expires_at'], name='job_offers_organiz_788138_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['skills'], name='job_offers_skills_4fa7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['job_type', 'location'], name='job_offers_job_typ_2c3a7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('offer', 'applicant')},
        ),
    ]
