# Generated by Django 4.2.28 on 2026-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('interview', 'Entrevista'), ('rejected', 'Rechazado'), ('hired', 'Contratado'), ('shortlisted', 'Preseleccionar')], default='pending', max_length=20),
        ),
    ]
