# Generated by Django 4.2.28 on 2026-03-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
