# Generated by Django 4.2.28 on 2026-08-31 20:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_joboffer_moderation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_job_id', models.UUIDField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_external', models.BooleanField(db_index=True, default=False)),
                ('external_apply_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('total_applications_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_purged', models.BooleanField(db_index=True, default=False)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historial de oferta',
                'verbose_name_plural': 'Historial de ofertas',
                'db_table': 'job_offer_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='joboffer',
            name='external_apply_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='is_external',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(blank=True, help_text='PDF máximo 1MB', null=True, upload_to='cvs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('interview', 'Entrevista'), ('rejected', 'Rechazado'), ('hired', 'Contratado'), ('shortlisted', 'Preseleccionar'), ('redirected', 'Redirigida / Aplicada externamente')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='expires_at',
            field=models.DateTimeField(help_text='Caduca automáticamente 30 días después de la creación si no se indica otra fecha.'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['is_external', 'expires_at'], name='job_offers_is_exte_529be5_idx'),
        ),
        migrations.AddField(
            model_name='jobofferhistory',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offer_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobofferhistory',
            index=models.Index(fields=['is_external', 'created_at'], name='job_offer_h_is_exte_5c4725_idx'),
        ),
        migrations.AddIndex(
            model_name='jobofferhistory',
            index=models.Index(fields=['is_purged', 'expired_at'], name='job_offer_h_is_purg_e81216_idx'),
        ),
    ]
