# Generated by Django 4.2.28 on 2026-04-30 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0002_match_posted_by_matchevent_posted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_starter', models.BooleanField(default=True)),
                ('position', models.CharField(blank=True, choices=[('goalkeeper', 'Portero'), ('defender', 'Defensa'), ('midfielder', 'Mediocampista'), ('forward', 'Delantero'), ('coach', 'Entrenador'), ('staff', 'Staff'), ('pitcher', 'Lanzador'), ('catcher', 'Receptor'), ('first_base', 'Primera Base'), ('second_base', 'Segunda Base'), ('third_base', 'Tercera Base'), ('shortstop', 'Shortstop'), ('left_field', 'Jardinero Izquierdo'), ('center_field', 'Jardinero Central'), ('right_field', 'Jardinero Derecho'), ('designated_hitter', 'Bateador Designado'), ('utility', 'Utility')], max_length=20)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('substitution_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='sports.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='sports.player')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_lineups', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='sports.team')),
            ],
            options={
                'db_table': 'match_lineups',
                'ordering': ['-is_starter', 'jersey_number'],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
