# Generated by Django 4.2.28 on 2026-04-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_matchlineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='is_on_field',
            field=models.BooleanField(default=True),
        ),
    ]
