# Generated by Django 4.2.28 on 2026-05-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_matchlineup_is_on_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('substituted', 'Sustituido'), ('injured', 'Lesionado'), ('suspended', 'Suspendido')], default='active', max_length=20),
        ),
    ]
