# Generated by Django 4.2.28 on 2026-05-11 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_match_finished_at_match_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds_before_pause', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='sports.match')),
            ],
            options={
                'db_table': 'match_periods',
                'ordering': ['period_number'],
                'unique_together': {('match', 'period_number')},
            },
        ),
    ]
