# Generated by Django 4.2.28 on 2026-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_matchperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='player',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cédula'),
        ),
    ]
