# Generated by Django 4.2.28 on 2026-05-14 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0008_player_email_player_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.URLField(verbose_name='URL de la imagen')),
                ('link_url', models.URLField(blank=True, verbose_name='URL de destino')),
                ('position', models.CharField(choices=[('home_hero', 'Home - Banner Principal'), ('home_sidebar', 'Home - Sidebar'), ('tournament_detail', 'Detalle de Torneo'), ('match_detail', 'Detalle de Partido'), ('standings_top', 'Tabla de Posiciones - Arriba'), ('standings_bottom', 'Tabla de Posiciones - Abajo'), ('footer', 'Footer'), ('popup', 'Popup Modal')], default='home_hero', max_length=30, verbose_name='Posición')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impresiones')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner Publicitario',
                'verbose_name_plural': 'Banners Publicitarios',
                'db_table': 'advertisement_banners',
                'ordering': ['position', 'display_order', '-created_at'],
            },
        ),
    ]
