# Generated by Django 4.2.28 on 2026-05-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_advertisementbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementbanner',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='sports.tournament', verbose_name='Torneo'),
        ),
    ]
