# Generated by Django 4.2.28 on 2026-05-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_advertisementbanner_tournament'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchlineup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='entry_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='matchlineup',
            unique_together={('match', 'player', 'entry_number')},
        ),
    ]
