# Generated by Django 4.2.28 on 2026-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_alter_matchlineup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Impresiones'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Impresiones'),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Impresiones'),
        ),
        migrations.AddField(
            model_name='matchperiod',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Impresiones'),
        ),
        migrations.AddField(
            model_name='player',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Impresiones'),
        ),
        migrations.AddField(
            model_name='team',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Impresiones'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Impresiones'),
        ),
    ]
