# Generated by Django 4.2.28 on 2026-07-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
        ('sports', '0013_tournament_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementbanner',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='advertising.classifiedadcampaign', verbose_name='Campaña'),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='advertising.tournamentsponsorship', verbose_name='Patrocinio'),
        ),
        migrations.AlterField(
            model_name='advertisementbanner',
            name='position',
            field=models.CharField(choices=[('home_hero', 'Home - Banner Principal'), ('home_sidebar', 'Home - Sidebar'), ('tournament_detail', 'Detalle de Torneo'), ('match_detail', 'Detalle de Partido'), ('standings_top', 'Tabla de Posiciones - Arriba'), ('standings_bottom', 'Tabla de Posiciones - Abajo'), ('jobs_list_top', 'Empleos - Listado'), ('job_detail', 'Empleo - Detalle'), ('listings_list_top', 'Inmuebles - Listado'), ('listing_detail', 'Inmueble - Detalle'), ('events_list_top', 'Eventos - Listado'), ('event_detail', 'Evento - Detalle'), ('footer', 'Footer'), ('popup', 'Popup Modal')], default='home_hero', max_length=30, verbose_name='Posición'),
        ),
    ]
