# Generated by Django 4.2.28 on 2026-07-02 16:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0014_advertisementbanner_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('group', 'Fase de grupos'), ('knockout', 'Eliminatoria'), ('friendly', 'Amistoso'), ('legacy', 'Liga simple')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='stats_counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format_template',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scoring_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='structure_mode',
            field=models.CharField(choices=[('legacy', 'Liga simple'), ('structured', 'Multi-fase')], default='legacy', max_length=20),
        ),
        migrations.CreateModel(
            name='TournamentPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('phase_type', models.CharField(choices=[('group_stage', 'Fase de grupos'), ('round_robin', 'Todos contra todos'), ('knockout', 'Eliminatoria'), ('placement', 'Partido por puesto')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'En curso'), ('finished', 'Finalizada')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('advancement_rules', models.JSONField(blank=True, default=dict)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='sports.tournament')),
            ],
            options={
                'db_table': 'tournament_phases',
                'ordering': ['order', 'name'],
                'unique_together': {('tournament', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('max_teams', models.PositiveSmallIntegerField(default=4)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sports.tournamentphase')),
            ],
            options={
                'db_table': 'competition_groups',
                'ordering': ['order', 'name'],
                'unique_together': {('phase', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='sports.competitiongroup'),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='sports.tournamentphase'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='sports.competitiongroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='sports.team')),
            ],
            options={
                'db_table': 'group_memberships',
                'unique_together': {('group', 'team')},
            },
        ),
    ]
