# Generated by Django 4.2.28 on 2026-07-02 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_tournament_structure_and_scoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(default='Eliminatoria', max_length=100)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='sports.tournamentphase')),
            ],
            options={
                'db_table': 'brackets',
            },
        ),
        migrations.CreateModel(
            name='BracketNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('round', models.CharField(choices=[('quarterfinal', 'Cuartos de final'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('third_place', 'Tercer puesto')], max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('home_source', models.JSONField(blank=True, default=dict)),
                ('away_source', models.JSONField(blank=True, default=dict)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='sports.bracket')),
                ('match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_node', to='sports.match')),
            ],
            options={
                'db_table': 'bracket_nodes',
                'ordering': ['round', 'position'],
                'unique_together': {('bracket', 'round', 'position')},
            },
        ),
    ]
