# Generated by Django 4.2.28 on 2026-07-02 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_tournament_rules_and_lineup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mercy_rule_enabled',
            field=models.BooleanField(default=True, help_text='Aplica knockout por diferencia de carreras (softbol).'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='regulation_innings',
            field=models.PositiveSmallIntegerField(default=7, help_text='Entradas reglamentarias (softbol: 7 estándar).'),
        ),
        migrations.CreateModel(
            name='MatchInning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('half', models.CharField(choices=[('top', 'Alta'), ('bottom', 'Baja')], max_length=6)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='sports.match')),
            ],
            options={
                'db_table': 'match_innings',
                'ordering': ['number', '-half'],
                'unique_together': {('match', 'number', 'half')},
            },
        ),
    ]
