# Generated by Django 4.2.28 on 2026-07-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0018_tournament_mercy_rule_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='inning_half',
            field=models.CharField(blank=True, choices=[('top', 'Alta'), ('bottom', 'Baja')], max_length=6),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='inning_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='rbi',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='at_bats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rbis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs_scored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Gol'), ('own_goal', 'Autogol'), ('yellow_card', 'Tarjeta Amarilla'), ('red_card', 'Tarjeta Roja'), ('substitution_in', 'Entra'), ('substitution_out', 'Sale'), ('penalty_goal', 'Gol de Penal'), ('penalty_missed', 'Penal Fallado'), ('assist', 'Asistencia'), ('expelled', 'Expulsado'), ('single', 'Sencillo'), ('double', 'Doble'), ('triple', 'Triple'), ('home_run', 'Jonrón'), ('walk', 'Base por bolas'), ('strikeout', 'Ponche'), ('run', 'Carrera anotada'), ('rbi', 'Carrera impulsada'), ('error', 'Error'), ('out', 'Out')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
