# Generated by Django 4.2.28 on 2026-07-10 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0019_matchevent_inning_half_matchevent_inning_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSuspension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('direct_red', 'Roja directa'), ('double_yellow', 'Doble amarilla'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('matches_count', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_player_suspensions', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_suspensions', to='sports.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='sports.player')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_player_suspensions', to=settings.AUTH_USER_MODEL)),
                ('suspended_until_match', models.ForeignKey(blank=True, help_text='Próximo partido programado que debe cumplir la sanción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_players', to='sports.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_suspensions', to='sports.tournament')),
            ],
            options={
                'db_table': 'player_suspensions',
                'ordering': ['-created_at'],
            },
        ),
    ]
