# Generated by Django 4.2.28 on 2026-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0022_tournament_list_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('registration', 'Inscripción'), ('active', 'En curso'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], db_index=True, default='active', max_length=20),
        ),
    ]
