# Generated by Django 4.2.28 on 2026-09-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0024_tournament_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketnode',
            name='round',
            field=models.CharField(choices=[('round_of_32', 'Dieciseisavos de final'), ('round_of_16', 'Octavos de final'), ('quarterfinal', 'Cuartos de final'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('third_place', 'Tercer puesto')], max_length=20),
        ),
    ]
