# Generated by Django 4.2.28 on 2026-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0025_alter_bracketnode_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='first_phase_qualified_per_group',
            field=models.PositiveSmallIntegerField(default=2, help_text='Equipos que clasifican por grupo en la primera fase.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='has_second_group_phase',
            field=models.BooleanField(default=False, help_text='Segunda fase de grupos antes de los playoffs.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_phase_assignment_method',
            field=models.CharField(blank=True, choices=[('RANDOM', 'Aleatoria'), ('MANUAL', 'Manual')], default='RANDOM', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_phase_groups_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Grupos de la segunda fase: 1 o 2.', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_phase_qualified_per_group',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Equipos que pasan de cada grupo de la segunda fase a playoffs.', null=True),
        ),
    ]
