# Generated by Django 4.2.28 on 2026-10-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0026_second_group_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
