# Generated by Django 4.2.28 on 2026-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0027_player_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Gol'), ('own_goal', 'Autogol'), ('yellow_card', 'Tarjeta Amarilla'), ('red_card', 'Tarjeta Roja'), ('substitution_in', 'Entra'), ('substitution_out', 'Sale'), ('penalty_goal', 'Gol de Penal'), ('penalty_missed', 'Penal Fallado'), ('assist', 'Asistencia'), ('expelled', 'Expulsado'), ('foul', 'Falta'), ('single', 'Sencillo'), ('double', 'Doble'), ('triple', 'Triple'), ('home_run', 'Jonrón'), ('walk', 'Base por bolas'), ('strikeout', 'Ponche'), ('run', 'Carrera anotada'), ('rbi', 'Carrera impulsada'), ('error', 'Error'), ('out', 'Out')], max_length=20),
        ),
    ]
