# Generated by Django 4.2.28 on 2026-09-01 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('ecommerce', '0002_subcategory_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('store_logo', models.URLField(blank=True, max_length=500)),
                ('organization', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='store_settings',
                    to='organizations.organization',
                )),
            ],
            options={
                'verbose_name': 'Configuración de tienda',
                'verbose_name_plural': 'Configuraciones de tienda',
                'db_table': 'ecommerce_store_settings',
            },
        ),
    ]
