# Generated by Django 4.2.28 on 2026-03-03 14:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')])),
                ('profile_schema', models.JSONField(default=dict, help_text='Schema JSON que define los campos dinámicos del perfil')),
                ('max_users', models.PositiveIntegerField(default=100)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['slug', 'is_active'], name='organizatio_slug_efe71a_idx'), models.Index(fields=['is_verified', 'created_at'], name='organizatio_is_veri_bc2bf0_idx')],
            },
        ),
    ]
