# Generated by Django 4.2.28 on 2026-07-02 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0013_tournament_moderation_status'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedAdCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('content_type', models.CharField(choices=[('job', 'Empleo'), ('real_estate', 'Bienes raíces'), ('event', 'Evento')], max_length=20)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('plan', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField()),
                ('link_url', models.URLField(blank=True)),
                ('target_reach', models.PositiveIntegerField(default=100)),
                ('frequency_cap', models.PositiveIntegerField(default=5)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('total_impressions', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credits_spent', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], db_index=True, default='active', max_length=20)),
                ('content_type_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classified_ad_campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentSponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('plan', models.CharField(choices=[('week', 'Semana'), ('month', 'Mes'), ('bimester', 'Bimestre')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField()),
                ('link_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credits_spent', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], db_index=True, default='active', max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_sponsorships', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='sports.tournament')),
            ],
            options={
                'db_table': 'tournament_sponsorships',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tournament', 'status', 'end_date'], name='tournament__tournam_c8a0bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdViewerImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('viewer_hash', models.CharField(db_index=True, max_length=64)),
                ('impression_count', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_impressions', to='advertising.classifiedadcampaign')),
            ],
            options={
                'db_table': 'ad_viewer_impressions',
                'unique_together': {('campaign', 'viewer_hash')},
            },
        ),
    ]
