# Generated by Django 4.2.28 on 2026-09-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentsponsorship',
            options={'ordering': ['created_at']},
        ),
    ]
