# Generated by Django 4.2.28 on 2026-10-05 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0027_player_phone'),
        ('advertising', '0002_alter_tournamentsponsorship_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_logs', to='sports.advertisementbanner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_impressions',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_at'], name='ad_impressi_viewed__a8e62c_idx'), models.Index(fields=['ad', 'viewed_at'], name='ad_impressi_ad_id_0c9ecc_idx')],
            },
        ),
    ]
