# Generated by Django 4.2.28 on 2026-03-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.BooleanField(default=False),
        ),
    ]
