# Generated by Django 4.2.28 on 2026-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('person', 'Persona'), ('company', 'Empresa')], default='person', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre de la empresa si el usuario es tipo empresa', max_length=255, null=True),
        ),
    ]
