# Generated by Django 4.2.28 on 2026-05-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_user_type_alter_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
