# Generated by Django 4.2.28 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_unlimited_credits",
            field=models.BooleanField(
                default=False,
                help_text="Si es True, el usuario no consume créditos al publicar.",
            ),
        ),
    ]
