# Generated by Django 4.2.28 on 2026-09-01

import os

from django.db import migrations, models

# Email del Super Admin Root original (owner). También se lee de settings/env.
PLATFORM_ROOT_EMAILS = ("carbalosamuel@hotmail.com",)


def _root_emails():
    emails = {email.strip().lower() for email in PLATFORM_ROOT_EMAILS if email}
    try:
        from django.conf import settings

        extra = getattr(settings, "PLATFORM_SUPERUSER_EMAIL", None)
        if extra:
            emails.add(str(extra).strip().lower())
    except Exception:
        pass
    env_email = (os.getenv("PLATFORM_SUPERUSER_EMAIL") or "").strip().lower()
    if env_email:
        emails.add(env_email)
    return {email for email in emails if email}


def backfill_admin_level(apps, schema_editor):
    """
    Evita que el Super Admin Root quede en nivel 0 tras añadir admin_level.
    1) Todos los is_superuser existentes → Nivel 1.
    2) El usuario owner de plataforma (email conocido / PLATFORM_SUPERUSER_EMAIL).
    3) Staff de plataforma sin organización (admins iniciales) → Nivel 1.
    """
    User = apps.get_model("authentication", "User")

    User.objects.filter(is_superuser=True).update(
        admin_level=1,
        is_staff=True,
        is_active=True,
        role="admin",
    )

    for email in _root_emails():
        qs = User.objects.filter(email__iexact=email)
        if not qs.exists():
            continue
        platform = qs.filter(organization__isnull=True)
        target = platform if platform.exists() else qs
        target.update(
            admin_level=1,
            is_superuser=True,
            is_staff=True,
            is_active=True,
            role="admin",
        )

    User.objects.filter(
        is_staff=True,
        organization__isnull=True,
        admin_level=0,
    ).update(admin_level=1)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_is_unlimited_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Usuario / staff estándar"),
                    (1, "Super Admin Root"),
                    (2, "Administrador delegado"),
                ],
                db_index=True,
                default=0,
                help_text="0=usuario, 1=Super Admin Root, 2=Administrador delegado.",
            ),
        ),
        migrations.RunPython(backfill_admin_level, noop_reverse),
    ]
