# Generated by Django 4.2.28 on 2026-09-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_sports_module_subscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditsubscriptiontransaction',
            new_name='credit_subs_user_id_81f491_idx',
            old_name='credit_sub_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='creditsubscriptiontransaction',
            new_name='credit_subs_transac_42ea69_idx',
            old_name='credit_sub_type_created_idx',
        ),
    ]
