# Generated by Django 4.2.28 on 2026-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('chat_message', 'Mensaje de chat'), ('job_status_change', 'Cambio estado postulación'), ('payment_success', 'Pago aprobado'), ('payment_pending', 'Pago pendiente'), ('payment_failed', 'Pago fallido')], db_index=True, max_length=30),
        ),
    ]
